runtime: python39
instance_class: F4_1G
inbound_services:
- warmup

#automatic_scaling:
#  min_instances: 5
#  max_instances: 100
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50

