apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: carbon_footprint_app-jvd
  name: carbon_footprint_app-jvd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carbon_footprint_app-jvd
    spec:
      containers:
      - image: carbon_footprint_app-jvd:latest
        name: carbon_footprint_app-jvd
        resources: {}
status: {}