apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: carbon_footprint_app-jvd
    app.kubernetes.io/managed-by: Helm
  name: carbon_footprint_app-jvd
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: carbon_footprint_app-jvd
  type: NodePort
status:
  loadBalancer: {}